### ISSUE TITLE
Refactor: 사용자 데이터 검증

### ISSUE THREAD

**Issue by hye-inA** [hye-inA/Zeroplace-Springboot#1]
## Issue 내용
> if문을 이용한 데이터 검증은 '코드 반복, 필드 누락 위험, 검증할 요소 많음'과 같은 문제점이 있음
        ex ) { "name": "          " }, { "name": ".....수십억 글자" } 로 들어간다면??
## Todo
- [x] Validation 의존성 사용 ( @NotBlank )

- [x] 데이터 값이 잘못 들어왔을때 client쪽에도 JSON 형태의 에러 응답을 받을 수 있도록 수정 

- [x] test 코드에서 name 필드에 ""(빈값), null 입력되었을때 정상적으로 검증되는지 확인 + jsonPath로 오류 메세지 커스텀

## 참고사항
- JUnit5 jsonPath 학습 ( 객체나 배열 검증할정도 )
